###
GET http://localhost:8080/api/session/current

###
POST http://localhost:8080/api/session/login HTTP/1.1
Content-Type: application/json

{
    "email": "israquirozzmail@gmail.com",
    "password": "Hola123$"
}

###
POST http://localhost:8080/api/session/logout

###
POST http://localhost:8080/api/session/register HTTP/1.1
Content-Type: application/json

{
    "first_name": "Prueba",
    "last_name": "Prueba 2",
    "email": "prueba2@prueba.com",
    "password": "Hola123$",
    "age": 22,
    "role": "user"
}

### GOOGLE
GET http://localhost:8080/api/session/google/callback